export const mockLinks = [
    {
        title: "Фитнес",
        icon: "/icons/heart.svg",
        labelName: "Название тега",
        stats: {
            clicks: 829,
            income: 312402,
        },
        link: "teamclick.app.tg/as75yf",
        name: "Teamclick",
        platform: "Instagram",
        customTitle: "",
        createdAt: "15.01.2024",
        income: 490,
    },
    {
        title: "Профессия",
        icon: "/icons/profession.svg",
        labelName: "Название тега",
        stats: {
            clicks: 827,
            income: 345,
        },
        link: "teamclick.app.tg/xz87ak",
        name: "JobClick",
        platform: "LinkedIn",
        customTitle: "",
        createdAt: "16.01.2024",
        income: 890,
    },
    {
        title: "Фитнес",
        icon: "/icons/heart.svg",
        labelName: "Название тега",
        stats: {
            clicks: 828,
            income: 3124,
        },
        link: "teamclick.app.tg/as75yf",
        name: "Teamclick",
        platform: "Instagram",
        customTitle: "",
        createdAt: "17.01.2024",
        income: 590,
    },
    {
        title: "Профессия",
        icon: "/icons/profession.svg",
        labelName: "Название тега",
        stats: {
            clicks: 1,
            income: 12,
        },
        link: "teamclick.app.tg/xz87ak",
        name: "JobClick",
        platform: "LinkedIn",
        customTitle: "",
        createdAt: "10.01.2024",
        income: 1890,
    },
];
