export const mockLinks = [
    {
        title: "Фитнес",
        icon: "./icons/heart.svg",
        labelName: "Название тега",
        stats: {
            clicks: 829,
            income: 312402,
        },
        link: "teamclick.app.tg/as75yf",
        name: "Teamclick",
        platform: "Instagram",
        customTitle: "",
        createdAt: "15.01.2024",
        income: 490,
    },
    {
        title: "Профессия",
        icon: "./icons/profession.svg",
        labelName: "Название тега",
        stats: {
            clicks: 0,
            income: 0,
        },
        link: "teamclick.app.tg/xz87ak",
        name: "JobClick",
        platform: "LinkedIn",
        customTitle: "",
        createdAt: "15.01.2024",
        income: 890,
    },
    {
        title: "Фитнес",
        icon: "./icons/heart.svg",
        labelName: "Название тега",
        stats: {
            clicks: 829,
            income: 312402,
        },
        link: "teamclick.app.tg/as75yf",
        name: "Teamclick",
        platform: "Instagram",
        customTitle: "",
        createdAt: "15.01.2024",
        income: 490,
    },
    {
        title: "Профессия",
        icon: "./icons/profession.svg",
        labelName: "Название тега",
        stats: {
            clicks: 0,
            income: 0,
        },
        link: "teamclick.app.tg/xz87ak",
        name: "JobClick",
        platform: "LinkedIn",
        customTitle: "",
        createdAt: "15.01.2024",
        income: 890,
    },
];
